owner: megasanjay
repo: upptime

sites:
  - name: Portfolio
    url: https://sanjaysoundarajan.dev
  - name: Colorize
    url: https://colorize.saso.one
  - name: AI Gallery Studio
    url: https://studio.sanjaysoundarajan.dev
  - name: Umami
    url: https://umami.sanjaysoundarajan.dev
  - name: Vue 3 Marquee Documentation
    url: https://vue3-marquee.vercel.app/
  - name: Vue 3 Lottie Documentation
    url: https://vue3-lottie.vercel.app/

assignees:
  - megasanjay

status-website:
  cname: status.sanjaysoundarajan.dev
  name: Uptime status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
