owner: megasanjay
repo: upptime

sites:
  - name: Portfolio
    url: https://sanjaysoundarajan.dev
  - name: Colorize
    url: https://colorize.saso.one
  - name: Sanity Studio
    url: https://studio.sanjaysoundarajan.dev
  - name: Umami
    url: https://umami.sanjaysoundarajan.dev
  - name: Vue 3 Marquee Documentation
    url: https://vue3marquee.sanjaysoundarajan.dev
  - name: Vue 3 Lottie Documentation
    url: https://vue3lottie.sanjaysoundarajan.dev

assignees:
  - megasanjay

status-website:
  cname: status.sanjaysoundarajan.dev
  name: Uptime status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
